// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// KeyvaultSecretListerExpansion allows custom methods to be added to
// KeyvaultSecretLister.
type KeyvaultSecretListerExpansion interface{}

// KeyvaultSecretNamespaceListerExpansion allows custom methods to be added to
// KeyvaultSecretNamespaceLister.
type KeyvaultSecretNamespaceListerExpansion interface{}
