// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	rest "k8s.io/client-go/rest"
	v1alpha1 "github.com/twendt/secret-controller/pkg/apis/secretcontroller/v1alpha1"
	"github.com/twendt/secret-controller/pkg/client/clientset/versioned/scheme"
)

type SecretcontrollerV1alpha1Interface interface {
	RESTClient() rest.Interface
	KeyvaultSecretsGetter
}

// SecretcontrollerV1alpha1Client is used to interact with features provided by the secretcontroller.twendt.de group.
type SecretcontrollerV1alpha1Client struct {
	restClient rest.Interface
}

func (c *SecretcontrollerV1alpha1Client) KeyvaultSecrets(namespace string) KeyvaultSecretInterface {
	return newKeyvaultSecrets(c, namespace)
}

// NewForConfig creates a new SecretcontrollerV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*SecretcontrollerV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &SecretcontrollerV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new SecretcontrollerV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *SecretcontrollerV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new SecretcontrollerV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *SecretcontrollerV1alpha1Client {
	return &SecretcontrollerV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *SecretcontrollerV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
