// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	secretcontrollerv1alpha1 "github.com/twendt/secret-controller/pkg/apis/secretcontroller/v1alpha1"
	versioned "github.com/twendt/secret-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/twendt/secret-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/twendt/secret-controller/pkg/client/listers/secretcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KeyvaultSecretInformer provides access to a shared informer and lister for
// KeyvaultSecrets.
type KeyvaultSecretInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.KeyvaultSecretLister
}

type keyvaultSecretInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKeyvaultSecretInformer constructs a new informer for KeyvaultSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKeyvaultSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKeyvaultSecretInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKeyvaultSecretInformer constructs a new informer for KeyvaultSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKeyvaultSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecretcontrollerV1alpha1().KeyvaultSecrets(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecretcontrollerV1alpha1().KeyvaultSecrets(namespace).Watch(options)
			},
		},
		&secretcontrollerv1alpha1.KeyvaultSecret{},
		resyncPeriod,
		indexers,
	)
}

func (f *keyvaultSecretInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKeyvaultSecretInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *keyvaultSecretInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&secretcontrollerv1alpha1.KeyvaultSecret{}, f.defaultInformer)
}

func (f *keyvaultSecretInformer) Lister() v1alpha1.KeyvaultSecretLister {
	return v1alpha1.NewKeyvaultSecretLister(f.Informer().GetIndexer())
}
