// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/twendt/secret-controller/pkg/client/clientset/versioned/typed/secretcontroller/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSecretcontrollerV1alpha1 struct {
	*testing.Fake
}

func (c *FakeSecretcontrollerV1alpha1) KeyvaultSecrets(namespace string) v1alpha1.KeyvaultSecretInterface {
	return &FakeKeyvaultSecrets{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSecretcontrollerV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
